# Generated by Django 4.2.11 on 2024-03-23 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_project', '0004_delete_topic_rename_myquery_response_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('chats', models.CharField(max_length=500)),
            ],
        ),
    ]
