# Generated by Django 4.2.11 on 2024-03-23 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot_project', '0006_clientinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('img', models.ImageField(blank=True, upload_to='')),
            ],
        ),
    ]
